using MySql.Data.Entity;
using ResumeStripper.Models;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace ResumeStripper.DAL
{
    [DbConfigurationType(typeof(MySqlEFConfiguration))]
    public class StripperContext : DbContext
    {
        //passes the connectionstring saved in the web.config to the DbContext
        public StripperContext() : base("MySqlCon")
        {
            Database.SetInitializer<StripperContext>(new DropCreateDatabaseAlways<StripperContext>());
        }

        //all of the required DbSets are generated by the line below
        public DbSet<CV> CVS { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //prevents data to be saved as (For example) "Skills" instead of "Skill"
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }
    }
}